mapbox/mapbox-sdk-py

- README.md
- mapbox/scripts/cli.py
- mapbox/scripts/geocoder.py
- setup.py
Also add more command line help.
Closes #18
> Change name to mbx

- mapbox/compat.py
- mapbox/scripts/cli.py
- mapbox/scripts/geocoder.py
- tests/test_cli.py
Also add lots of help.
Closes #20
> Move access token option to group

- mapbox/__init__.py
- tests/test_cli.py
- tests/test_geocoder.py
- updates endpoints
- rounds precision of `proximity` flag & reverse geocoding
- tests for ^^^ 
@sgillies mind have a quick look?
> geocoder v5

- README.rst
- mapbox/__init__.py
- mapbox/services/upload.py
- setup.py
- tests/test_upload.py
Initial implementation of the Upload API. Needs some review, see overview in [example usage](https://github.com/mapbox/mapbox-sdk-py/blob/3a11e2d55ab4f1333c15820aab54aec87368a6c9/mapbox/services/upload.py#L10)
> Upload API

- mapbox/services/geocoding.py
- tests/test_cli.py
- tests/test_geocoder.py
In the case of the geocoder, `json() == geojson()` but we'll do it for consistency
> Geocoder response geojson method

- CHANGES
- mapbox/services/uploads.py
- tests/test_upload.py
> Rename extract to create.

- README.rst
> update readme with new service endpoints

- mapbox/services/uploads.py
- tests/test_upload.py
> add name to upload method

- CHANGES
- README.rst
- mapbox/services/directions.py
- tests/test_directions.py
And profile param is moved to the directions method.
Closes #60
Closes #61
> route -> directions

- CHANGES
- mapbox/services/base.py
- tests/test_base.py
> Send unique User-Agent header

- mapbox/services/base.py
- mapbox/services/uploads.py
- tests/test_base.py
- tests/test_staticmaps.py
- tests/test_upload.py
This test, once passing, should give us 100% coverage.
However, we're back to square one with finding a mock solution for s3 and boto.
> Cover 100 quest

- mapbox/services/uploads.py
- tests/test_upload.py
TODO in another PR: convert mock responses to test fixtures.
> Add upload test and boto3 session monkeypatching

- docs/mapmatching.md
- mapbox/__init__.py
- mapbox/services/mapmatching.py
- tests/test_mapmatching.py
This is close to complete, needs review but otherwise good to go.
closes #41
> initial implementation of map matching api

- README.rst
- mapbox/services/mapmatching.py
- tests/test_mapmatching.py
A couple of details I missed in the first PR:
* add to README
* validate features
* kwarg for gps precision
> More map matching

- docs/geocoding.md
- mapbox/services/base.py
- mapbox/services/datasets.py
- mapbox/services/directions.py
- mapbox/services/distance.py
- mapbox/services/geocoding.py
- mapbox/services/mapmatching.py
- mapbox/services/static.py
- mapbox/services/surface.py
- mapbox/services/uploads.py
- setup.py
- tests/test_base.py
- tests/test_directions.py
The base service class can use an HTTP cache.
Closes #100.
> Refactor to produce a base service class.

- docs/geocoding.md
Geocoding doctests that are written to fit well with the API docs.
> Our API docs and SDK doctests are BFFs

- CHANGES
- mapbox/services/uploads.py
- tests/test_upload.py
- tox.ini
Uses multipart uploading when helpful.
Closes #116
> Use boto's high level upload_file() method

- mapbox/services/datasets.py
- mapbox/services/directions.py
- mapbox/services/distance.py
- mapbox/services/geocoding.py
- mapbox/services/mapmatching.py
- mapbox/services/static.py
- mapbox/services/surface.py
- mapbox/services/uploads.py
In the Static API, I was able to consolidate quite a bit.
Closes #102.
> Clean up URI templating

- docs/surface.md
- mapbox/encoding.py
- tests/test_encoding.py
- tests/test_surface.py
fixes #127 
checked the results against https://developers.google.com/maps/documentation/utilities/polylineutility 👍
> polyline coordinate order

- docs/geocoding.md
- mapbox/services/geocoding.py
- tests/test_geocoder.py
Ready for 👀  @KaiBot3000 @sgillies
> limit reverse geocoding results

- mapbox/services/uploads.py
- tests/test_upload.py
> add patch mode

- CHANGES
- docs/geocoding.md
- mapbox/__init__.py
- mapbox/services/uploads.py
- setup.py
- tests/test_upload.py
For version 0.11.0. This can support a progress bar for mapbox-upload from mapbox-cli-py (https://github.com/mapbox/mapbox-cli-py/pull/86).
> Add a S3 upload callback and require boto3>=1.4

- CHANGES
- mapbox/services/base.py
- mapbox/services/datasets.py
- mapbox/services/directions.py
- mapbox/services/distance.py
- mapbox/services/geocoding.py
- mapbox/services/mapmatching.py
- mapbox/services/static.py
- mapbox/services/surface.py
- mapbox/services/uploads.py
- mapbox/utils.py
- tests/test_base.py
> Make API host configurable via Service keyword arg or env var

- mapbox/services/uploads.py
> Catch 429 responses on the credentials endpoint

- .travis.yml
- docs/analytics.md
- docs/directions.md
- mapbox/__init__.py
- mapbox/errors.py
- mapbox/services/analytics.py
- setup.py
- tests/test_analytics.py
Here's the first cut for analytics-sdk. 
@batpad, @perrygeo Can you take a look at it. Will be glad to get suggestions to improve it.
> Analytics sdk

- docs/geocoding.md
Also, make header keys title-case for consistency with docs. Resolves #178
> No 'x-rate-limit-remaining' header

- .travis.yml
- setup.cfg
Universal wheels (py2 and py3) but only release on python 3.6 to avoid multiple upload attempts
> Automated release to create universal wheels

- mapbox/services/uploads.py
- tests/test_upload.py
> validate tileset name length

- mapbox/__init__.py
- mapbox/services/tokens.py
- setup.py
- tests/test_tokens.py
Have added support for listing of tokens and tests for listing, creation of tokens and temporary tokens. Will add other endpoints in the same PR after review for these,
> Tokens api support

- CHANGES
- docs/matrix.md
- mapbox/__init__.py
- mapbox/encoding.py
- mapbox/services/matrix.py
- tests/test_matrix.py
- tests/test_surface.py
> Add class for the Matrix API V1

- CHANGES
- mapbox/services/uploads.py
- tests/test_upload.py
Resolves #202.
Can be merged before the other PRs for the same milestone. It is independent.
> Deprecate account kwarg in favor of 'username'

- mapbox/services/analytics.py
- mapbox/services/datasets.py
> Include numpy-style docstrings for Analytics and Datasets services

- docs/api/mapbox.services.rst
- docs/index.rst
- mapbox/services/surface.py
The docs are hidden. The service warns when it is called.
Resolves #221
> Warn about Surface deprecation

- docs/index.rst
This attempts to address #244.  Thank you!
> Fix links in doc index

- README.rst
- docs/index.rst
- docs/tilequery.md
- mapbox/__init__.py
- mapbox/services/tilequery.py
- tests/test_tilequery.py
This attempts to address #255.  I would be happy to make changes to the code, tests, etc.  Thank you!
> Tilequery API

- docs/tilequery.md
This attempts to correct an error in a prior pull request.  Thank you!
> Correct error in tilequery.md

- tests/test_tilequery.py
This attempts to correct an error in a prior pull request.  Thank you!
> Correct error in test_tilequery.py

- README.rst
- docs/analytics.md
- docs/datasets.md
- docs/directions.md
- docs/geocoding.md
- docs/index.rst
- docs/mapmatching.md
- docs/maps.md
- docs/matrix.md
- docs/static.md
- docs/static_style.md
- docs/surface.md
- docs/tilequery.md
- docs/uploads.md
- mapbox/services/geocoding.py
Do not merge until API documentation changes land. This PR updates links to match the new URL structure.
cc @mapbox/docs @sgillies
> [DNM] Updates URLs for API documentation
